site_name: Java-9.org
site_url: http://www.java-9.org
repo_url: https://github.com/java-9/java-9.github.io
##repo_name: GitHub
site_author: Sven Ruppert
google_analytics: ['UA-87714600-1', 'java-9.org']

theme: readthedocs
markdown_extensions:
    - toc:
        permalink: True
pages:
- Home: index.md
- JEP102: JEP102.md
- JEP110: JEP110.md
- JEP213: JEP213.md
- JEP259: JEP259.md
- JEP264: JEP264.md
- JEP266: JEP266.md
- JEP269: JEP269.md


- java.lang:
    - 'StackTraceElement' : 'java.lang/StackTraceElement.md'
    - 'StrictMath' : 'java.lang/StrictMath.md'
- java.util:
    - 'Optional' : 'java.util/Optional.md'
- java.util.streams:
    - 'Streams' : 'java.util.streams/Stream.md'
